# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: clang-format
  name: clang-format
  entry: clang-format-hooks
  description: Formats C/CPP code
  files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
  language: python
