# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: check-clang-format
  name: Validate C/C++ source format with clang-format
  entry: clang-format-hook
  description: Formats C/CPP code
  language: python
  files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
