
# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python
cache: pip
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=lint SKIP_CODECOV=true
    - python: 3.6
      env: TOXENV=pre-commit-cpp SKIP_CODECOV=true
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

addons:
  apt:
    update: true
    packages:
      - clang-format

script:
  - pip install --upgrade pip
  - pip install -U tox
  - tox

after_success:
  - test "$SKIP_CODECOV" = true || test -z "$CODECOV_TOKEN" || pip install codecov && codecov -X gcov

notifications:
  email: false
