
# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-format

script:
  - pip install --upgrade pip
  - pip install tox
  - tox -e ${TOXENV}

notifications:
  email: false
